server:  
  port: ${PORT:3333}

spring:
  data:
  mongodb:
    host: localhost
    port: 27017
    username: micro 
    password: micro
      
#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: false